/**
 * HR domain audit action catalog (Sprint 23, docs/domains/hr.md), the
 * exact `MAINTENANCE_AUDIT_ACTIONS` `<entity>.<event>` naming convention.
 */
export const HR_AUDIT_ACTIONS = {
  DEPARTMENT_CREATED: 'hr.department.created',
  DEPARTMENT_UPDATED: 'hr.department.updated',
  DEPARTMENT_ACTIVATED: 'hr.department.activated',
  DEPARTMENT_DEACTIVATED: 'hr.department.deactivated',
  POSITION_CREATED: 'hr.position.created',
  POSITION_UPDATED: 'hr.position.updated',
  POSITION_ACTIVATED: 'hr.position.activated',
  POSITION_DEACTIVATED: 'hr.position.deactivated',
  EMPLOYEE_CREATED: 'hr.employee.created',
  EMPLOYEE_UPDATED: 'hr.employee.updated',
  EMPLOYEE_DEPARTMENT_ASSIGNED: 'hr.employee.department_assigned',
  EMPLOYEE_POSITION_ASSIGNED: 'hr.employee.position_assigned',
  EMPLOYEE_MANAGER_ASSIGNED: 'hr.employee.manager_assigned',
  EMPLOYEE_USER_LINKED: 'hr.employee.user_linked',
  EMPLOYEE_USER_UNLINKED: 'hr.employee.user_unlinked',
  EMPLOYEE_ACTIVATED: 'hr.employee.activated',
  EMPLOYEE_SUSPENDED: 'hr.employee.suspended',
  EMPLOYEE_REACTIVATED: 'hr.employee.reactivated',
  EMPLOYEE_SEPARATED: 'hr.employee.separated',
  EMPLOYEE_DOCUMENT_ADDED: 'hr.employee.document_added',
  EMPLOYEE_DOCUMENT_UPDATED: 'hr.employee.document_updated',
  ONBOARDING_STARTED: 'hr.onboarding.started',
  ONBOARDING_TASK_COMPLETED: 'hr.onboarding.task_completed',
  ONBOARDING_COMPLETED: 'hr.onboarding.completed',

  // Sprint 24 — Attendance, Policies, Training
  WORK_SCHEDULE_CREATED: 'hr.work_schedule.created',
  WORK_SCHEDULE_UPDATED: 'hr.work_schedule.updated',
  WORK_SCHEDULE_ACTIVATED: 'hr.work_schedule.activated',
  WORK_SCHEDULE_DEACTIVATED: 'hr.work_schedule.deactivated',
  EMPLOYEE_WORK_SCHEDULE_ASSIGNED: 'hr.employee.work_schedule_assigned',
  ATTENDANCE_SIGNED_IN: 'hr.attendance.signed_in',
  ATTENDANCE_SIGNED_OUT: 'hr.attendance.signed_out',
  ATTENDANCE_ADMINISTRATIVE_ENTRY: 'hr.attendance.administrative_entry',
  ATTENDANCE_REVIEWED: 'hr.attendance.reviewed',
  ATTENDANCE_CORRECTION_REQUESTED: 'hr.attendance.correction_requested',
  ATTENDANCE_CORRECTION_APPROVED: 'hr.attendance.correction_approved',
  ATTENDANCE_CORRECTION_REJECTED: 'hr.attendance.correction_rejected',
  ATTENDANCE_CORRECTION_CANCELLED: 'hr.attendance.correction_cancelled',
  POLICY_CREATED: 'hr.policy.created',
  POLICY_UPDATED: 'hr.policy.updated',
  POLICY_ARCHIVED: 'hr.policy.archived',
  POLICY_VERSION_CREATED: 'hr.policy.version_created',
  POLICY_VERSION_PUBLISHED: 'hr.policy.version_published',
  POLICY_ACKNOWLEDGED: 'hr.policy.acknowledged',
  TRAINING_COURSE_CREATED: 'hr.training_course.created',
  TRAINING_COURSE_UPDATED: 'hr.training_course.updated',
  TRAINING_COURSE_ACTIVATED: 'hr.training_course.activated',
  TRAINING_COURSE_ARCHIVED: 'hr.training_course.archived',
  TRAINING_ASSIGNED: 'hr.training.assigned',
  TRAINING_STARTED: 'hr.training.started',
  TRAINING_COMPLETED: 'hr.training.completed',
  TRAINING_CANCELLED: 'hr.training.cancelled',
} as const;
