import { MetricDefinition } from './reporting.types';

/**
 * Sprint 45 — Reporting & Business Intelligence Foundation (docs/domains/reporting.md
 * "Metric Registry" / "KPI Dictionary"). Typed, discoverable individual metrics —
 * metadata only, resolved by `ReportingService`'s small `METRIC_RESOLVERS` map
 * (each resolver delegates to the one authoritative domain service/query named in
 * `authoritativeSource`, never a second calculation of the same figure — brief §4).
 *
 * This registry deliberately covers BOTH metrics new this sprint and metrics that
 * already existed before Sprint 45 (gross profit, AR/AP totals, inventory value) —
 * the brief's own Definition of Done requires "KPI dictionary covers every
 * implemented KPI," not only the ones Sprint 45 happened to add code for.
 */
export const METRIC_REGISTRY: MetricDefinition[] = [
  {
    id: 'finance.net-revenue',
    displayName: 'Net Revenue',
    description: 'Revenue recognized in the General Ledger for the period, net of sales returns.',
    domain: 'FINANCE',
    unit: 'CURRENCY',
    aggregation: 'SUM',
    authoritativeSource:
      'FinancialStatementService.getProfitAndLoss().revenue (GL REVENUE accounts, net of SALES_RETURNS)',
    timeBasis: 'PERIOD',
    supportedFilters: ['period', 'comparison'],
    requiredPermission: 'finance.reports.view',
    drillDownReportId: 'sales-performance',
    availability: 'AVAILABLE',
  },
  {
    id: 'finance.gross-profit',
    displayName: 'Gross Profit',
    description: 'Net revenue less cost of sales, for the period.',
    domain: 'FINANCE',
    unit: 'CURRENCY',
    aggregation: 'DERIVED',
    authoritativeSource: 'FinancialStatementService.getProfitAndLoss().grossProfit',
    timeBasis: 'PERIOD',
    supportedFilters: ['period', 'comparison'],
    requiredPermission: 'finance.reports.view',
    availability: 'AVAILABLE',
  },
  {
    id: 'finance.gross-margin-percent',
    displayName: 'Gross Margin %',
    description: 'Gross profit as a percentage of net revenue. Null (not 0%) when revenue is zero.',
    domain: 'FINANCE',
    unit: 'PERCENT',
    aggregation: 'DERIVED',
    authoritativeSource: 'FinancialStatementService.getProfitAndLoss().grossMarginPercent',
    timeBasis: 'PERIOD',
    supportedFilters: ['period', 'comparison'],
    requiredPermission: 'finance.reports.view',
    availability: 'AVAILABLE',
  },
  {
    id: 'finance.receivables-outstanding',
    displayName: 'Receivables Outstanding',
    description: 'Total unpaid, uncredited customer invoice balance as of now.',
    domain: 'FINANCE',
    unit: 'CURRENCY',
    aggregation: 'POINT_IN_TIME',
    authoritativeSource: 'AccountsReceivableService.getSummary().totalOutstanding',
    timeBasis: 'POINT_IN_TIME',
    supportedFilters: [],
    requiredPermission: 'finance.reports.view',
    drillDownReportId: 'receivables',
    availability: 'AVAILABLE',
  },
  {
    id: 'finance.receivables-overdue',
    displayName: 'Receivables Overdue',
    description: 'The portion of outstanding receivables already past its due date.',
    domain: 'FINANCE',
    unit: 'CURRENCY',
    aggregation: 'POINT_IN_TIME',
    authoritativeSource: 'AccountsReceivableService.getSummary().totalOverdue',
    timeBasis: 'POINT_IN_TIME',
    supportedFilters: [],
    requiredPermission: 'finance.reports.view',
    drillDownReportId: 'receivables',
    availability: 'AVAILABLE',
  },
  {
    id: 'finance.payables-outstanding',
    displayName: 'Payables Outstanding',
    description: 'Total unpaid, uncredited supplier invoice obligation as of now.',
    domain: 'FINANCE',
    unit: 'CURRENCY',
    aggregation: 'POINT_IN_TIME',
    authoritativeSource: 'AccountsPayableService.getSummary().totalOutstanding',
    timeBasis: 'POINT_IN_TIME',
    supportedFilters: [],
    requiredPermission: 'finance.reports.view',
    drillDownReportId: 'payables',
    availability: 'AVAILABLE',
  },
  {
    id: 'finance.payables-overdue',
    displayName: 'Payables Overdue',
    description: 'The portion of outstanding payables already past its due date.',
    domain: 'FINANCE',
    unit: 'CURRENCY',
    aggregation: 'POINT_IN_TIME',
    authoritativeSource: 'AccountsPayableService.getSummary().totalOverdue',
    timeBasis: 'POINT_IN_TIME',
    supportedFilters: [],
    requiredPermission: 'finance.reports.view',
    drillDownReportId: 'payables',
    availability: 'AVAILABLE',
  },
  {
    id: 'inventory.value',
    displayName: 'Inventory Value',
    description:
      'Total inventory value as of now — quantity on hand × moving weighted-average cost, across every product and location.',
    domain: 'INVENTORY',
    unit: 'CURRENCY',
    aggregation: 'POINT_IN_TIME',
    authoritativeSource: 'InventoryValuationService.getValuation().totals.grandTotal',
    timeBasis: 'POINT_IN_TIME',
    supportedFilters: ['locationId'],
    requiredPermission: 'finance.reports.view',
    drillDownReportId: 'inventory-position',
    availability: 'AVAILABLE',
  },
  {
    id: 'inventory.low-stock-count',
    displayName: 'Low-Stock Items',
    description: 'Count of products at or below a reorder threshold.',
    domain: 'INVENTORY',
    unit: 'COUNT',
    aggregation: 'COUNT',
    authoritativeSource: 'None — no reorderPoint/minimumStock field exists on Product.',
    timeBasis: 'POINT_IN_TIME',
    supportedFilters: [],
    requiredPermission: 'finance.reports.view',
    availability: 'BLOCKED_DATA_GAP',
    limitation:
      'No reorder-point or minimum-stock field exists on Product. Implementing this metric honestly requires a schema addition, deliberately deferred — see docs/domains/reporting.md "Known Data Gaps".',
  },
  {
    id: 'sales.net-sales-order-count',
    displayName: 'Sales Order Count',
    description:
      'Count of non-draft, B2B sales orders placed in the period (D2C orders are reported separately by the existing D2C admin dashboard — see docs/domains/reporting.md "D2C").',
    domain: 'SALES',
    unit: 'COUNT',
    aggregation: 'COUNT',
    authoritativeSource:
      'SalesPerformanceReportService (direct SalesOrder.count, source=B2B, status != DRAFT)',
    timeBasis: 'PERIOD',
    supportedFilters: ['period', 'comparison', 'status'],
    requiredPermission: 'sales.dashboard.view',
    drillDownReportId: 'sales-performance',
    availability: 'AVAILABLE',
  },
  {
    id: 'production.yield-percent',
    displayName: 'Production Yield %',
    description:
      'Accepted output as a percentage of planned quantity, averaged across production orders completed in the period.',
    domain: 'PRODUCTION',
    unit: 'PERCENT',
    aggregation: 'DERIVED',
    authoritativeSource:
      'ProductionPerformanceReportService (ProductionOrder.plannedQuantity vs ProductionRun.acceptedQuantity)',
    timeBasis: 'PERIOD',
    supportedFilters: ['period', 'comparison'],
    requiredPermission: 'production.order.view',
    drillDownReportId: 'production-performance',
    availability: 'AVAILABLE',
  },
  {
    id: 'production.material-cost',
    displayName: 'Production Material Cost',
    description:
      'Total material cost (WIP value at completion) for production orders completed in the period, from posted journal entries.',
    domain: 'PRODUCTION',
    unit: 'CURRENCY',
    aggregation: 'SUM',
    authoritativeSource:
      'ProductionMaterialIssueRepository.getTotalWipValue (GL-sourced), summed per completed order',
    timeBasis: 'PERIOD',
    supportedFilters: ['period', 'comparison'],
    requiredPermission: 'production.order.view',
    drillDownReportId: 'production-performance',
    availability: 'AVAILABLE',
    limitation: 'Materials only — no labour or overhead costing exists in this codebase.',
  },
  {
    id: 'hr.active-headcount',
    displayName: 'Active Headcount',
    description: 'Count of employees with EmploymentStatus = ACTIVE as of now.',
    domain: 'HR',
    unit: 'COUNT',
    aggregation: 'COUNT',
    authoritativeSource: 'EmployeeRepository.countGroupedByStatus()',
    timeBasis: 'POINT_IN_TIME',
    supportedFilters: ['departmentId'],
    requiredPermission: 'hr.employee.view',
    drillDownReportId: 'workforce-summary',
    availability: 'AVAILABLE',
  },
  {
    id: 'hr.leave-days-approved',
    displayName: 'Approved Leave Days',
    description: 'Approved leave days taken in the period.',
    domain: 'HR',
    unit: 'COUNT',
    aggregation: 'SUM',
    authoritativeSource: 'None — no Leave/LeaveRequest model exists in this codebase.',
    timeBasis: 'PERIOD',
    supportedFilters: ['period'],
    requiredPermission: 'hr.employee.view',
    availability: 'BLOCKED_DATA_GAP',
    limitation:
      'No Leave/LeaveRequest/LeaveBalance model exists anywhere in this codebase. EmploymentStatus.ON_LEAVE is defined but never written by any code path. This metric requires new domain modelling, out of scope for a reporting-only sprint.',
  },
  {
    id: 'operations.pending-approvals',
    displayName: 'Pending Approvals',
    description: 'Count of workflow step instances currently awaiting action (status ACTIVE).',
    domain: 'OPERATIONS',
    unit: 'COUNT',
    aggregation: 'COUNT',
    authoritativeSource:
      'OperationalExceptionsReportService (direct WorkflowStepInstance.count, status=ACTIVE)',
    timeBasis: 'POINT_IN_TIME',
    supportedFilters: [],
    requiredPermission: 'workflow.instance.view',
    drillDownReportId: 'operational-exceptions',
    availability: 'AVAILABLE',
  },
  {
    id: 'operations.overdue-work-orders',
    displayName: 'Overdue Work Orders',
    description:
      'Count of maintenance work orders past their planned end date and not yet completed.',
    domain: 'OPERATIONS',
    unit: 'COUNT',
    aggregation: 'COUNT',
    authoritativeSource: 'MaintenanceOverviewService.getOverview().overdueWorkOrders',
    timeBasis: 'POINT_IN_TIME',
    supportedFilters: [],
    requiredPermission: 'maintenance.work_order.view',
    drillDownReportId: 'operational-exceptions',
    availability: 'AVAILABLE',
  },
  {
    id: 'operations.failed-notifications',
    displayName: 'Failed Notifications',
    description: 'Count of email and WhatsApp delivery attempts currently in a FAILED state.',
    domain: 'OPERATIONS',
    unit: 'COUNT',
    aggregation: 'COUNT',
    authoritativeSource:
      'OperationalExceptionsReportService (direct EmailDelivery/WhatsAppDelivery.count, status=FAILED)',
    timeBasis: 'POINT_IN_TIME',
    supportedFilters: [],
    requiredPermission: 'notification.email.view',
    drillDownReportId: 'operational-exceptions',
    availability: 'AVAILABLE',
  },
];

export function getMetricDefinition(metricId: string): MetricDefinition | undefined {
  return METRIC_REGISTRY.find((metric) => metric.id === metricId);
}
