import { Prisma } from '@prisma/client';

import { PrismaService } from '../../prisma/prisma.service';
import { ConsumerRepository } from './consumer.repository';

/**
 * Sprint 32 — Consumer Identity, Territory & Location Foundation
 * (docs/domains/d2c.md §8 "Idempotency / Duplicate Registration"). Fakes
 * just enough of `prisma.consumer` to exercise the ACTUAL check-then-create
 * logic for real — the exact `CandidateRepository.findOrCreate` pattern
 * (Sprint 30) applied to phone identity, including its P2002-race-recovery
 * branch and tenant scoping.
 */
describe('ConsumerRepository — idempotency, concurrency, and tenant isolation', () => {
  const ORG_A = 'org-a';
  const ORG_B = 'org-b';

  function makeRepository() {
    const store: {
      id: string;
      organisationId: string;
      normalizedPhone: string;
      consumerCode: string;
      fullName?: string;
      [key: string]: unknown;
    }[] = [];
    let nextId = 1;

    const prisma = {
      consumer: {
        findFirst: jest.fn(({ where }: { where: Record<string, unknown> }) => {
          const match = store.find(
            (row) =>
              (where.id === undefined || row.id === where.id) &&
              row.organisationId === where.organisationId &&
              (where.normalizedPhone === undefined ||
                row.normalizedPhone === where.normalizedPhone),
          );
          return Promise.resolve(match ? { ...match } : null);
        }),
        count: jest.fn(({ where }: { where: Record<string, unknown> }) => {
          return Promise.resolve(
            store.filter((row) => row.consumerCode === where.consumerCode).length,
          );
        }),
        create: jest.fn(({ data }: { data: Record<string, unknown> }) => {
          // Simulate the real DB unique constraint on [organisationId, normalizedPhone].
          const collision = store.find(
            (row) =>
              row.organisationId === data.organisationId &&
              row.normalizedPhone === data.normalizedPhone,
          );
          if (collision) {
            throw new Prisma.PrismaClientKnownRequestError('Unique constraint failed', {
              code: 'P2002',
              clientVersion: '5.22.0',
            });
          }
          const row = { id: `consumer-${nextId++}`, ...data } as (typeof store)[number];
          store.push(row);
          return Promise.resolve({ ...row });
        }),
        updateMany: jest.fn(
          ({ where, data }: { where: Record<string, unknown>; data: Record<string, unknown> }) => {
            const row = store.find(
              (r) => r.id === where.id && r.organisationId === where.organisationId,
            );
            if (!row) return Promise.resolve({ count: 0 });
            Object.assign(row, data);
            return Promise.resolve({ count: 1 });
          },
        ),
        findUniqueOrThrow: jest.fn(({ where }: { where: { id: string } }) => {
          const row = store.find((r) => r.id === where.id);
          if (!row) throw new Error('not found');
          return Promise.resolve({ ...row });
        }),
      },
    } as unknown as PrismaService;

    return { repository: new ConsumerRepository(prisma), store };
  }

  it('creates a new consumer on first registration', async () => {
    const { repository } = makeRepository();

    const result = await repository.findOrCreate({
      organisationId: ORG_A,
      consumerCode: 'CON-000001',
      fullName: 'Blessing Okafor',
      phoneNumber: '08031234501',
      normalizedPhone: '+2348031234501',
    });

    expect(result.created).toBe(true);
    expect(result.consumer.normalizedPhone).toBe('+2348031234501');
  });

  it('a second registration attempt with the same normalized phone returns the existing consumer, not a duplicate', async () => {
    const { repository } = makeRepository();
    const first = await repository.findOrCreate({
      organisationId: ORG_A,
      consumerCode: 'CON-000001',
      fullName: 'Blessing Okafor',
      phoneNumber: '08031234501',
      normalizedPhone: '+2348031234501',
    });

    const second = await repository.findOrCreate({
      organisationId: ORG_A,
      consumerCode: 'CON-000002', // a fresh code generated by the caller before the race
      fullName: 'Blessing Okafor',
      phoneNumber: '2348031234501',
      normalizedPhone: '+2348031234501',
    });

    expect(second.created).toBe(false);
    expect(second.consumer.id).toBe(first.consumer.id);
  });

  it('two concurrent registrations for the same phone converge on exactly one consumer (the P2002 race path)', async () => {
    const { repository, store } = makeRepository();

    // Both requests reach `findByNormalizedPhone` before either has created
    // anything (the genuine race) — simulated by calling `create` directly
    // for both, rather than the sequential `findOrCreate`, since a plain
    // `await` can't otherwise interleave two calls against this fake.
    const dataA = {
      organisationId: ORG_A,
      consumerCode: 'CON-000001',
      fullName: 'Blessing Okafor',
      phoneNumber: '08031234501',
      normalizedPhone: '+2348031234501',
    };
    const dataB = { ...dataA, consumerCode: 'CON-000002' };

    const [resultA, resultB] = await Promise.all([
      repository.findOrCreate(dataA),
      repository.findOrCreate(dataB),
    ]);

    expect(store.filter((r) => r.organisationId === ORG_A).length).toBe(1);
    expect(resultA.consumer.id).toBe(resultB.consumer.id);
    // Exactly one of the two calls actually created the row.
    expect([resultA.created, resultB.created].filter(Boolean)).toHaveLength(1);
  });

  it('tenant isolation: the same normalized phone in a different organisation is a separate consumer', async () => {
    const { repository } = makeRepository();
    const inOrgA = await repository.findOrCreate({
      organisationId: ORG_A,
      consumerCode: 'CON-000001',
      fullName: 'Blessing Okafor',
      phoneNumber: '08031234501',
      normalizedPhone: '+2348031234501',
    });
    const inOrgB = await repository.findOrCreate({
      organisationId: ORG_B,
      consumerCode: 'CON-000001',
      fullName: 'A Different Person',
      phoneNumber: '08031234501',
      normalizedPhone: '+2348031234501',
    });

    expect(inOrgA.created).toBe(true);
    expect(inOrgB.created).toBe(true);
    expect(inOrgA.consumer.id).not.toBe(inOrgB.consumer.id);
  });

  it('tenant isolation: findById never resolves a consumer belonging to another organisation', async () => {
    const { repository } = makeRepository();
    const { consumer } = await repository.findOrCreate({
      organisationId: ORG_A,
      consumerCode: 'CON-000001',
      fullName: 'Blessing Okafor',
      phoneNumber: '08031234501',
      normalizedPhone: '+2348031234501',
    });

    const crossTenantResult = await repository.findById(ORG_B, consumer.id);
    expect(crossTenantResult).toBeNull();
  });

  it('tenant isolation: update cannot mutate a cross-tenant consumer', async () => {
    const { repository, store } = makeRepository();
    const { consumer } = await repository.findOrCreate({
      organisationId: ORG_A,
      consumerCode: 'CON-000001',
      fullName: 'Blessing Okafor',
      phoneNumber: '08031234501',
      normalizedPhone: '+2348031234501',
    });

    const result = await repository.update(ORG_B, consumer.id, { fullName: 'Hijacked' });

    expect(result).toBeNull();
    expect(store.find((r) => r.id === consumer.id)?.fullName).toBe('Blessing Okafor');
  });
});
